### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by WillSewell**

### CODE REVIEW

**Comment by tibbe** [comment]
I would recommend switching to criterion instead, as I'm no longer maintaining this library. Unless you want to become the maintainer it is. :)

**Comment by WillSewell** [comment]
We are using criterion, but we are very interested in tracking down anomalous latencies. I like the fact that benchpress prints the max latency as well as the 95th and 99th percentiles. I haven't found this kind of functionality in criterion; it seems to focus more on the average performance. unless I'm missing something.

**Comment by tibbe** [comment]
You're welcome to use the library if it suits you. I will merge this change but I don't have time to actively maintain this library, so if you depend on it it would be great if you'd take it over.

**Comment by WillSewell** [comment]
I would be happy to take over maintainership :)

**Comment by tibbe** [comment]
Great. Give me your Hackage username and I'll set you as the maintainer. Should I transfer the repo to your GitHub account (@WillSewell)? You will need to delete any clones you have there first.

**Comment by WillSewell** [comment]
Username is "willsewell". It's up to you whether you want to transfer the repo or not. I'm happy to if you do. Thank you!

**Comment by tibbe** [comment]
Added you as a Hackage maintainer.

**Comment by WillSewell** [comment]
Thanks :)

**Pull request merged**
